How does unsqueeze help us to solve certain broadcasting problems?

In [ ]:
"""
In broadcasting, it broadcast on the dim=1 or there must be matching dimension with existing tensor, for this purpose we use the unsqueeze method
"""

What is the downside of having activations with a standard deviation too far away from 1?

In [ ]:
"""
If the activations with standard deviation too far away from 1 occur it will create the problem of vanishing or exploading gradient on the basis 
of direction in which it is far away from 1. 
If its too small than during backpropogation the weigths will be updated very slowly due to small value of gradient caused by activation. 
If the value is too large than during backpropogation the gradient will be too lager, so weights and biases update excessively and may lead to untable 
behavior.
Another problem is the lack of generalization in the final model. If the value in the activation have standard deviation is far away from standard 
deviation of the on which the network was trained on the network will perform poorly.

"""

How do we show the actual contents of the memory used for a tensor?

In [ ]:
"""
For this purpose we have the .storage property of the tensor which shows us the tensor content as it is store in the memory.
"""

When adding a vector of size 3 to a matrix of size 3×3, are the elements of the vector added
to each row or each column of the matrix?

In [ ]:
from operator import add
import numpy as np
a = np.array([1,1,1])
b = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
print(a, b)
res_list = list(map(add, b, a))
print(res_list)
res_list = list(map(add, a, b))
print(res_list)
# vector is being added row wise to matrix

[1 1 1] [[1 1 1]
 [2 2 2]
 [3 3 3]]
[array([2, 2, 2]), array([3, 3, 3]), array([4, 4, 4])]
[array([2, 2, 2]), array([3, 3, 3]), array([4, 4, 4])]


Do broadcasting and expand_as result in increased memory use? Why or why not?

In [ ]:
"""
No, they do not as expanding a tesor does not allocate new memory, it only creates a new view on the existing tensor.
"""

Implement matmul using Einstein summation.

In [1]:
import numpy as np

def matmul(A, B):
  return np.einsum('ij, jk -> ik', A, B)

A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

result = matmul(A, B)
print(result)

[[19 22]
 [43 50]]


What does a repeated index letter represent on the lefthand side of einsum?

In [ ]:
"""
It represents the summation over that index.
"""

What are the three rules of Einstein summation notation? Why?

In [ ]:
"""
Each index can appear at most twice in any term.
Repeated indices are implicitly summed over.
Each term must contain identical non-repeated indices.
"""

What are the forward pass and backward pass of a neural network?

In [ ]:
"""
An epoch is composed of a forward and a backward pass, in forward pass we start from the input layer all the way to the top that is the output layer, and 
in forward pass only the processing takes place no values are update of changed. In backwards pass we go from top layer(output) to (input layer) while 
updating the weights and bias trying to mitigate the error
"""

Why do we need to store some of the activations calculated for intermediate layers in the
forward pass?

In [ ]:
"""
The purpose of it is that these activation of the intermidiate layers are used as inputs to the next layer during the forward pass and in order to 
calculate the activation of the next layer. They also contribute in the calculation of the gradients with respect to the weights and biases of the 
intermidiate layers. So storing them help to access them directly during the backward pass instead of recalculating these values.
"""

What is the downside of having activations with a standard deviation too far away from 1?

In [ ]:
"""
If the activations with standard deviation too far away from 1 occur it will create the problem of vanishing or exploading gradient on the basis 
of direction in which it is far away from 1. 
If its too small than during backpropogation the weigths will be updated very slowly due to small value of gradient caused by activation. 
If the value is too large than during backpropogation the gradient will be too lager, so weights and biases update excessively and may lead to untable 
behavior.
Another problem is the lack of generalization in the final model. If the value in the activation have standard deviation is far away from standard 
deviation of the on which the network was trained on the network will perform poorly.

"""

How can weight initialization help avoid this problem?

In [2]:
"""
One of the helps it does is that if we initialize the weights using a distributaion which has a standard deviation to 1. This solves the problems 
of vanishing gradient which occurs if the activation with a standard deviation too far away from 1 are present.
"""

'\nOne of the helps it does is that if we initialize the weights using a distributaion which has a standard deviation to 1. This solves the problems \nof vanishing gradient which occurs if the activation with a standard deviation too far away from 1 are present.\n'